[a,b] = [-1, 1];  

q(x) = 1/eps, eps = 0.05, 

f(x) = (1/eps + pi^2)cos(pi*x), 

u = cos(pi*x) + exp((x-1)/eps^(1/2)) + exp(-(x+1)/eps^(1/2))

In [2]:
import numpy as np
np.set_printoptions(precision=10, suppress=True, linewidth=160)

In [3]:
a, b = -1, 1
eps = 0.05

q = 1/eps

f = lambda x: (1/eps + np.pi**2)*np.cos(np.pi*x) 

u = lambda x: np.cos(np.pi*x) + np.exp(((x-1)/eps**(1/2))) + np.exp(-(x+1)/eps**(1/2)) #точное решение


ua, ub = u(-1), u(1)
print(ua, ub)

0.00013048243864866027 0.00013048243864862815


In [5]:
N = 20
h = (b-a)/N
nodes = np.arange(a,b+h,h)
fi = np.vectorize(f)(nodes)
qi = q
ui = np.vectorize(u)(nodes)
#print(nodes)

AA = np.zeros((N+1, N+1))
AA[0, 0] = 1
AA[-1, -1] = 1
j = 0
for i in range(1, len(AA)-1):
    AA[i][j] = -1/(h**2)
    AA[i][j+1] = 2/(h**2)+qi
    AA[i][j+2] = -1/(h**2)
    j+=1
#print(AA)

#нижняя диагональ
A = np.zeros(N+1)
A[1:N] = -1/(h**2)
print('A:', A, len(A))

#главная диагональ
B = np.zeros(N+1)
B[0], B[-1] = 1, 1
B[1:N] = 2/(h**2)+qi
print('B:', B, len(B))

#верхняя диагональ
C = np.zeros(N+1)
C[1:N] = -1/(h**2)
print('C:', C, len(C))

#правая часть системы
F = np.zeros(N+1)
F[0], F[-1] = ua, ub
#F[1], F[-2] = fi[1] + ua/(h**2), fi[-2] + ub/(h**2)
F[1: N] = fi[1: N]
print('F:', F, len(F))


A: [   0. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.    0.] 21
B: [  1. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220. 220.   1.] 21
C: [   0. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.    0.] 21
F: [  0.0001304824 -28.4076819048 -24.1650175757 -17.5569129588  -9.2302153752  -0.             9.2302153752  17.5569129588  24.1650175757  28.4076819048
  29.8696044011  28.4076819048  24.1650175757  17.5569129588   9.2302153752   0.            -9.2302153752 -17.5569129588 -24.1650175757 -28.4076819048
   0.0001304824] 21


## Метод прогонки

In [234]:
def progonka(A, B, C, F):
    """
    метод прогонки,
    A, B, C - диагональ под главной, главная дагональ и диагональ над главной соответственно,
    F - правая часть системы
    """
    n = len(A)
    alpha = np.zeros(n)
    beta = np.zeros(n)
    x = np.zeros(n)
    alpha[0] = -C[0]/B[0]
    beta[0] = F[0]/B[0]

    for i in range(1, n):
        alpha[i] = -C[i-1]/(A[i-1]*alpha[i-1] + B[i-1])
        beta[i] = (F[i-1] - A[i-1]*beta[i-1])/(A[i-1]*alpha[i-1] + B[i-1])

    x[n-1] = (F[n-1] - A[n-1]*beta[n-1])/(A[n-1]*alpha[n-1] + B[n-1])

    for i in range(n-1, 0, -1):
        x[i-1] = alpha[i]*x[i] + beta[i]

    return np.array(x)


In [235]:
ui

array([ 0.0001304824, -0.3114451293, -0.3998561231, -0.3258697279, -0.141084819 ,  0.1080987806,  0.3792648763,  0.6344675381,  0.8416267901,  0.9762252075,
        1.022845782 ,  0.9762252075,  0.8416267901,  0.6344675381,  0.3792648763,  0.1080987806, -0.141084819 , -0.3258697279, -0.3998561231, -0.3114451293,
        0.0001304824])

In [236]:
progonka(A, B, C, F)

array([ 0.0001304824, -0.3099414812, -0.397924922 , -0.3238431714, -0.1389609256,  0.110431289 ,  0.3819097613,  0.637468032 ,  0.8449507797,  0.9797735075,
        1.0264741177,  0.9797735075,  0.8449507797,  0.637468032 ,  0.3819097613,  0.110431289 , -0.1389609256, -0.3238431714, -0.397924922 , -0.3099414812,
        0.0001304824])

In [237]:
max(abs(ui - progonka(A, B, C, F)))

0.003628335706417296

In [238]:
h**2

0.010000000000000002

## Метод Якоби

In [239]:
AA = np.zeros((N+1, N+1))
AA[0, 0] = 1
AA[-1, -1] = 1
j = 0
for i in range(1, len(AA)-1):
    AA[i][j] = -1/(h**2)
    AA[i][j+1] = 2/(h**2)+qi
    AA[i][j+2] = -1/(h**2)
    j+=1
print(AA)

[[   1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [-100.  220. -100.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0. -100.  220. -100.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0. -100.  220. -100.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0. -100.  220. -100.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0. -100.  220. -100.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0. -100.  220. -100.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0. -100.  220. -100.    0.    0.    0.    0.    0.    0.    0.

In [240]:
def Jacobi(A, b, eps=0.001, x=None):
    if x is None:
        x = np.zeros(A.shape[0])
                                                                                                                                                                
    D = np.diag(A)
    R = A - np.diagflat(D)

    c = 0                                                                                                                                            
    while np.linalg.norm(A@x - b) > eps:
        c += 1
        x = (b - R@x) / D

    return (x, c)

In [241]:
x, c = Jacobi(AA, F)
print(x)
c

[ 0.0001304824 -0.3099435632 -0.3979290265 -0.3238492139 -0.1389687331  0.1104218772  0.3818990147  0.637456172   0.8449381459  0.9797603602  1.0264608335
  0.9797603602  0.8449381459  0.637456172   0.3818990147  0.1104218772 -0.1389687331 -0.3238492139 -0.3979290265 -0.3099435632  0.0001304824]


99

In [242]:
ui

array([ 0.0001304824, -0.3114451293, -0.3998561231, -0.3258697279, -0.141084819 ,  0.1080987806,  0.3792648763,  0.6344675381,  0.8416267901,  0.9762252075,
        1.022845782 ,  0.9762252075,  0.8416267901,  0.6344675381,  0.3792648763,  0.1080987806, -0.141084819 , -0.3258697279, -0.3998561231, -0.3114451293,
        0.0001304824])

In [243]:
max(abs(x - ui))

0.0036150515522122006

In [244]:
np.linalg.norm(AA@x - F)

0.0009446992926631771

## Метод релаксации

In [80]:
def Relaxation(A, b, w=1, eps=0.01, x=None):
    n = len(A)
    if x is None:
        x = np.zeros(n)
        
    c = 0
    while np.linalg.norm(A@x - b) > eps:
        c += 1
        for i in range(n):
            s1 = -sum(A[i][j] * x[j] for j in range(i))/A[i][i]
            s2 = -sum(A[i][j] * x[j] for j in range(i + 1, n))/A[i][i]
            x[i] = (1-w)*x[i] +  w*(b[i]/A[i][i] + s1 + s2)

    return (x, c)

In [81]:
x, c = Relaxation(AA, F)
print(c, max(abs(x - ui)))

40 0.0035309318534324508


In [82]:
bestw, minc = 1, c
for w in np.arange(0.1, 2, 0.1):
    x, c = Relaxation(AA, F, w)
    if (c <= minc):
        bestw = w
        minc = c

    print(f"w={round(w, 1)},    loss={max(abs(x - ui))},    c={c}")

print(bestw, minc)

w=0.1,    loss=0.003488377477003146,    c=773
w=0.2,    loss=0.003488478647883264,    c=366
w=0.3,    loss=0.0034924149286970074,    c=231
w=0.4,    loss=0.003493936386519847,    c=163
w=0.5,    loss=0.0034946339843429097,    c=122
w=0.6,    loss=0.0035003342960138184,    c=95
w=0.7,    loss=0.00349803765439316,    c=75
w=0.8,    loss=0.003514419224970311,    c=61
w=0.9,    loss=0.0035137659382220576,    c=49
w=1.0,    loss=0.0035309318534324508,    c=40
w=1.1,    loss=0.0035411177365609614,    c=32
w=1.2,    loss=0.003557432108974634,    c=25
w=1.3,    loss=0.0036039022918297192,    c=19
w=1.4,    loss=0.003627922377482884,    c=19
w=1.5,    loss=0.003625618952060261,    c=21
w=1.6,    loss=0.003627341095988834,    c=24
w=1.7,    loss=0.0035982899142148472,    c=30
w=1.8,    loss=0.0036428955066660773,    c=46
w=1.9,    loss=0.0036085243755856755,    c=89
1.4000000000000001 19


## Метод наискорейшего спуска

In [86]:
def GradDesc(A, b, eps=0.01, x=None):
    n = len(A)
    if x is None:
        x = np.zeros(n)
        
    c = 0
    r = A@x - b #вектор невязки
    while np.linalg.norm(r) > eps:
        c += 1
        alpha = (r.T@r)/(A@r@r.T)
        x = x - alpha*r
        r = A@x - b

    return (x, c)

In [87]:
x, c = GradDesc(AA, F)
print(c, max(abs(x - ui)))

76 0.0035318788717935146


## Метод сопряженных градиентов

In [94]:
def ConjGrad(A, b, eps=0.01, x=None):
    n = len(A)
    if x is None:
        x = np.zeros(n)
        
    c = 0
    r = b - A@x
    p = r
    while np.linalg.norm(r) > eps:
        c += 1
        alpha = (r.T@r)/(p.T@A@p)
        x = x + alpha*r
        r1 = r - alpha*A@p

        beta = r1.T@r1/(r.T@r)
        p = r1 + beta*p
        r = r1

    return (x, c)

In [95]:
x, c = ConjGrad(AA, F)
print(c, max(abs(x - ui)))

10 0.3033906641519447
